package userbalancecoins

import (
	"battles/internal/answer"
	"battles/internal/userbalancecoins/userbalancecoins_models"
)

type UserBalanceCoinsRepo interface {
	CreateBalanceByUserPublicAddressAndAmountAndTicker(command *userbalancecoins_models.CommandCreateBalanceByUserPublicAddressAndAmountAndTicker) *answer.Answer
	ReadUserBalanceCoinsByUserPublicAddress(query *userbalancecoins_models.QueryReadUserBalanceCoinsByUserPublicAddress) *answer.Answer
	ReadUserBalanceAllCoinsByUserPublicAddress(query *userbalancecoins_models.QueryReadUserBalanceAllCoinsByUserPublicAddress) *answer.Answer
	ReadCountByUserIdAndTicker(query *userbalancecoins_models.QueryReadCountByUserIdAndTicker) *answer.Answer
	CreateBalanceByUserIdAmountSpentAndTicker(command *userbalancecoins_models.CommandCreateBalanceByUserIdAmountSpentAndTicker) *answer.Answer
	UpdateBalanceByUserIdAmountSpentAndTicker(command *userbalancecoins_models.CommandUpdateBalanceByUserIdAmountSpentAndTicker) *answer.Answer
}
